### ISSUE TITLE
add file 失败？

### ISSUE THREAD

**Issue by xunge** [HelloYym/VirtualDiskandFileSystem#1]
你好，代码对我帮助很大，但是不是很理解为什么 操作2中 add file 中调用的 writeDisk() 方法 需要判断输入的文件名是否存在？并且如果文件名和硬盘中的文件名相同会删除文件。。

同时一些代码不是很懂还望解答

1. read_halfword() 函数中的 num 运算过程？

```
num = second_byte << 8 | first_byte;
```

还望解答，万分感谢！

**Comment by HelloYym** [comment]
1. writeDisk() 方法的作用是新建一个文件，如果发现当前目录已经有同名文件，就把之前的文件删除。
2. Directory 类是 FAT 文件系统的目录项，具体结构可以参考这个链接中的表格，https://blog.csdn.net/sikuon/article/details/76397831
3. read_halfword() 中的 num 是计算实际的数字，因为存储中是前 8 位表示低位，后 8 位表示高位，这里读取时要转换一下，这个是大端和小端模式的问题。



杨煜溟
Mobile: 158-6715-8098
Email: yangym@zju.edu.cn

在 2018年10月20日 +0800 PM7:53，xunge <notifications@github.com>，写道：

**Comment by xunge** [comment]
十分感谢回答，但是我在add file添加文件时无论输入任何文件名都提示我文件不存在。如程序第346行所示

```c++
    if((filefp=fopen(nam,"rb"))==NULL){
        printf("The file does not exist.");
        getchar();
        return;
    }
```

1. nam 是否应该和readDisk() 函数一样需要和root连接？
2. 既然前面已经删除了同名文件，为何还要判断文件是否存在？
3. fopen 只是在内存中分配一个 file 结构单元，为何在执行程序时指针为空？
4. 上述代码注释掉后程序直接停止运行，写入文件失败

还望有时间的时候进行解答，万分感谢

**Comment by xunge** [comment]
还请指教

```
#define FAT1    136
#define FAT2    192
#define DIR     248
#define DATA    280
```

程序初始定义的参数值是如何找到的？

**Comment by HelloYym** [comment]
add file 的意思是把本地文件系统的文件添加到我们的虚拟磁盘的 FAT 文件系统中，
因此 int index = seekFILE(nam); 这句是在虚拟磁盘文件系统中查找这个要添加的文件是否存在，
之后通过 fopen 获取 filefp 文件指针，这个文件对应的是本地文件系统的文件，也就是要被复制的原始文件。


杨煜溟
Mobile: 158-6715-8098
Email: yangym@zju.edu.cn

在 2018年10月21日 +0800 AM11:08，xunge <notifications@github.com>，写道：

**Comment by HelloYym** [comment]
这个应该就是人为规定的

杨煜溟
Mobile: 158-6715-8098
Email: yangym@zju.edu.cn

在 2018年10月23日 +0800 AM9:18，xunge <notifications@github.com>，写道：

**Comment by xunge** [comment]
感谢解答！写的真棒！
